import { z } from 'zod';

const objectIdRegex = /^[0-9a-fA-F]{24}$/;

export const createLeaveSchema = z.object({
  _id: z.string().regex(objectIdRegex).optional(), // usually generated by MongoDB
  employeeId: z.string().regex(objectIdRegex, "Invalid ObjectId for employeeId"),
  type: z.enum(['Annuel', 'Maladie', 'Non payé', 'Autre']),
  startDate: z.string().refine(d => !isNaN(Date.parse(d)), {
    message: "Invalid startDate format"
  }),
  endDate: z.string().refine(d => !isNaN(Date.parse(d)), {
    message: "Invalid endDate format"
  }),
  days: z.number().min(0.5).optional(), // auto-calculated if not provided
  reason: z.string().optional(),
  status: z.enum(['En attente', 'Approuvé', 'Rejeté', 'Annulé']).default('En attente'),
  approvedBy: z.string().regex(objectIdRegex, "Invalid ObjectId for approvedBy").optional(),
  approvedAt: z.string().refine(d => !isNaN(Date.parse(d)), {
    message: "Invalid approvedAt format"
  }).optional(),
  rejectionReason: z.string().optional(),
  createdBy: z.string().regex(objectIdRegex, "Invalid ObjectId for createdBy").optional(),
  overrideBalance: z.boolean().optional()
});

export const updateLeaveSchema = createLeaveSchema.partial();

export const leaveBulkCreateSchema = z.object({
  leaves: z.array(createLeaveSchema),
});

export const leaveBulkUpdateSchema = z.object({
  leaves: z.array(createLeaveSchema.partial()),
});

export type LeaveCreateInput = z.infer<typeof createLeaveSchema>;
export type LeaveUpdateInput = z.infer<typeof updateLeaveSchema>;
export type LeaveBulkCreateInput = z.infer<typeof leaveBulkCreateSchema>;
export type LeaveBulkUpdateInput = z.infer<typeof leaveBulkUpdateSchema>;